# Generated by Django 5.0.4 on 2024-07-23 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_is_award_actor_is_awarded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='full_name',
            field=models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='director',
            name='full_name',
            field=models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
