# Generated by Django 5.0.4 on 2024-07-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_actor_full_name_alter_director_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
