# Generated by Django 5.0.4 on 2024-06-28 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_artefact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artefact',
            new_name='Artifact',
        ),
    ]
